language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
script: "bundle exec rake test"
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
